name: Auto Update Kodi Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *' # Läuft vollautomatisch jeden Tag um 04:00 Uhr nachts
  workflow_dispatch: # Erlaubt es dir, das Update jederzeit manuell per Klick zu starten

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wichtig: Erlaubt GitHub Actions, die neuen Dateien ins Repo zu pushen
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Fetch Latest Addon Files
        run: |
          python _fetch_addons.py

      - name: Run Repo Generator
        run: |
          python _repo_generator.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-update: Neue Add-on Versionen eingepflegt"
          git push
